### ISSUE TITLE
Incomplete compilation (o_strings.c is not compile due of Makefile error)

### ISSUE THREAD

**Issue by pacome35220** [rudreais/fed-in-the-abyss#3]
**Describe the bug**
- Compilation doesn't seem complete because of [this line in Makefile](https://github.com/rudreais/fed-in-the-abyss/blob/c5669e6cd3a74701867467ecf3c18b7968ea6641/Makefile#L20)
GCC replace `*.c` by `lib/objects/string.c`. But there are 2 files in `lib/objects/` and only one is compile.
- A file is also created : `lib/objects/*.o` instead of `lib/objects/string.o`

**To Reproduce**
1. Go to **project root**
2. ~~Click on '....'~~ **Compile** `make`
3. ~~Scroll down to '....'~~
4. See error : `make` **output**

**Expected behavior**
To compile all source file: 
- You should use a wildcard like : `$(wildcard *.c)`.
- But I recommand to list each source file.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rudreais** [comment]
`strings` file located in the objects directory are to be deleted. there's no use in that, just a little fun i had at the beginning of the project. if you have the will, delete and refactor from that
